# Veri Tipleri ve Dönüşümler
### Amaç:
1. Veri setindeki sütunların veri tiplerini incele ve gerekli dönüşümleri gerçekleştir
  
### Adımlar:
1. Veri setini yüklemek
2. Veri tiplerini incele
3. Sayısal kategorik ve tarih sütunlarını belirle
4. Sipariş tarihi ni datetime sütununa dönüştür
5. Tarih sütunundan yeni özellikler üret
6. Kategorik sütunları kategori tipine dönüştür
7. Dönüşüm sonrası kontrol
8. Güncellenmiş veri setini kaydet.

In [6]:
import pandas as pd

In [8]:
# 1 veri setini yüklemek
dataFrame = pd.read_csv("e_ticaret_veri_seti_eksik_veriler_duzenlendi.csv")

In [10]:
# 2 veri tiplerini incele
dataFrame.dtypes

siparis_id          object
musteri_id          object
siparis_tarihi      object
sehir               object
bolge               object
kategori            object
urun_adi            object
adet                 int64
birim_fiyat        float64
indirim_orani      float64
kargo_ucreti       float64
odeme_turu          object
musteri_tipi        object
teslimat_gunu      float64
musteri_puani      float64
iade_durumu         object
kar_marji_orani    float64
toplam_tutar       float64
dtype: object

In [12]:
# 3. sayısal, kategorik ve tarih sutunlarını belirle
sayisal_sutunlar = dataFrame.select_dtypes(include = ["float64","int64"]).columns
kategorik_sutunlar = dataFrame.select_dtypes(include = ["object"]).columns
tarih_sutunlari = dataFrame["siparis_tarihi"]

In [22]:
# 4. sipariş tarihini datetime tipine dönüştür
dataFrame["siparis_tarihi"] = pd.to_datetime(dataFrame["siparis_tarihi"])
dataFrame["siparis_tarihi"].dtypes

dtype('<M8[ns]')

In [26]:
# 5. tarih sütununda yeni özellikler türet
# yıl, ay, gün ve hafta günü bilgisini yazdır
dataFrame["siparis_yili"] = dataFrame["siparis_tarihi"].dt.year
dataFrame["siparis_ay"] = dataFrame["siparis_tarihi"].dt.month
dataFrame["siparis_gunu"] = dataFrame["siparis_tarihi"].dt.day
dataFrame["haftanin_gunu"] = dataFrame["siparis_tarihi"].dt.day_name()
dataFrame.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ay,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,...,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,...,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,...,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday

In [34]:
dataFrame.columns

Index(['siparis_id', 'musteri_id', 'siparis_tarihi', 'sehir', 'bolge',
       'kategori', 'urun_adi', 'adet', 'birim_fiyat', 'indirim_orani',
       'kargo_ucreti', 'odeme_turu', 'musteri_tipi', 'teslimat_gunu',
       'musteri_puani', 'iade_durumu', 'kar_marji_orani', 'toplam_tutar',
       'siparis_yili', 'siparis_ay', 'siparis_gunu', 'haftanin_gunu'],
      dtype='object')

## **NOT**

### df.drop('Unnamed: 0', axis=1, inplace=True) 

Bu fonksiyondaki axis = 1 --> sutunları ,  axis = 0 ---> satırları temsil eder.

### inplace = True tablodan da siler, fakat inplace = False sadece değeri geri döndürür satırı tabloyu silmez.

In [44]:
dataFrame.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,...,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ay,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,...,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,...,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,...,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,...,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,...,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday

In [50]:
pd.set_option('display.max_columns', None)
# Burada ki None yeri ekranda gösterilecek olan parametre sayısını temsil eder bize

In [52]:
dataFrame.head()

,siparis_id,musteri_id,siparis_tarihi,sehir,bolge,kategori,urun_adi,adet,birim_fiyat,indirim_orani,kargo_ucreti,odeme_turu,musteri_tipi,teslimat_gunu,musteri_puani,iade_durumu,kar_marji_orani,toplam_tutar,siparis_yili,siparis_ay,siparis_gunu,haftanin_gunu
0,SIP101125,MUS1391,2024-01-13 17:06:00,İstanbul,Marmara,Kozmetik,Nemlendirici,1,414.51,0.05,49.9,Kredi Kartı,Yeni,3.0,5.0,Hayır,0.220,443.68,2024,1,13,Saturday
1,SIP100837,MUS1347,2025-03-17 21:13:00,Gaziantep,Güneydoğu Anadolu,Spor,Dambıl Seti,2,1475.15,0.10,29.9,Banka Kartı,VIP,4.0,1.0,Hayır,0.361,2685.17,2025,3,17,Monday
2,SIP100050,MUS1066,2025-06-03 12:42:00,Kayseri,İç Anadolu,Kitap,İş Analitiği Rehberi,1,289.02,0.05,29.9,Kredi Kartı,Mevcut,6.0,2.0,Hayır,0.348,304.47,2025,6,3,Tuesday
3,SIP100263,MUS1008,2024-08-10 15:13:00,Antalya,Akdeniz,Kitap,Girişimcilik,5,194.78,0.00,49.9,Kapıda Ödeme,Yeni,3.0,5.0,Hayır,0.250,1023.80,2024,8,10,Saturday
4,SIP100707,MUS1291,2024-08-19 08:24:00,Gaziantep,Güneydoğu Anadolu,Elektronik,Powerbank,3,841.80,0.05,39.9,Dijital Cüzdan,Mevcut,4.0,5.0,Hayır,0.280,2439.03,2024,8,19,Monday

In [54]:
# 6. kategorik sütunları kategori tipine dönüştür
kategorik_donusum_sutunlar = [
    "sehir",
    "kategori",
    "urun_adi",
    "odeme_turu",
    "musteri_tipi",
    "haftanin_gunu"
]

for sutun in kategorik_donusum_sutunlar:
    dataFrame[sutun] = dataFrame[sutun].astype("category")

In [58]:
dataFrame.dtypes

siparis_id                 object
musteri_id                 object
siparis_tarihi     datetime64[ns]
sehir                    category
bolge                      object
kategori                 category
urun_adi                 category
adet                        int64
birim_fiyat               float64
indirim_orani             float64
kargo_ucreti              float64
odeme_turu               category
musteri_tipi             category
teslimat_gunu             float64
musteri_puani             float64
iade_durumu                object
kar_marji_orani           float64
toplam_tutar              float64
siparis_yili                int32
siparis_ay                  int32
siparis_gunu                int32
haftanin_gunu            category
dtype: object

In [60]:
# 8. güncellenmiş veri setini kaydet
dataFrame.to_csv("e_ticaret_veri_seti_veri_tipleri_duzenlendi.csv",index = False, encoding = "utf-8-sig")